db:
  image: mysql:5.7
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mckingdom
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
  ports:
    - 3306:3306
